# Apache Airflow HelmRelease
# dependsOn: [role-database-server, role-ingress, role-certificates]
# Variables substituted by postBuild
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: default
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: airflow
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    executor: LocalExecutor
    defaultAirflowTag: "2.9.3"
    airflowVersion: "2.9.3"

    webserver:
      defaultUser:
        enabled: true
        role: Admin
        username: admin
        email: admin@example.com
        firstName: admin
        lastName: user
        password: admin
      resources:
        requests:
          memory: "384Mi"
          cpu: "200m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      startupProbe:
        failureThreshold: 24
        timeoutSeconds: 30

    scheduler:
      resources:
        requests:
          memory: "384Mi"
          cpu: "200m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      startupProbe:
        failureThreshold: 12
        timeoutSeconds: 60

    triggerer:
      enabled: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "300m"

    ingress:
      web:
        enabled: true
        ingressClassName: ${OKDP_INGRESS_CLASS}
        annotations:
          cert-manager.io/cluster-issuer: ${OKDP_CLUSTER_ISSUER}
        hosts:
          - name: "airflow-default.${OKDP_INGRESS_SUFFIX}"
            tls:
              enabled: true
              secretName: airflow-tls
          - name: "airflow.${OKDP_INGRESS_SUFFIX}"
            tls:
              enabled: true
              secretName: airflow-tls

    postgresql:
      enabled: false

    data:
      metadataConnection:
        user: airflow
        pass: airflow123
        protocol: postgresql
        host: ${OKDP_DB_HOST}
        port: ${OKDP_DB_PORT}
        db: ${OKDP_AIRFLOW_DB_NAME}
        sslmode: disable

    redis:
      enabled: false
    workers:
      replicas: 0
    dagProcessor:
      enabled: false
    flower:
      enabled: false
    pgbouncer:
      enabled: false
    statsd:
      enabled: false

    dags:
      mountPath: /opt/airflow/dags
      persistence:
        enabled: false
      gitSync:
        enabled: true
        repo: "https://github.com/OKDP/okdp-sandbox.git"
        branch: "main"
        ref: "HEAD"
        depth: 1
        subPath: "examples/airflow/dags"
        period: "60s"

    migrateDatabaseJob:
      enabled: true
      useHelmHooks: false
    createUserJob:
      useHelmHooks: false

    config:
      core:
        load_examples: "False"
