# Role: Database Server (PostgreSQL Operator)
# Deploys CloudNativePG operator + PostgreSQL cluster instance
# Apps that need a database dependsOn this role
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: role-database-server
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sources
  sourceRef:
    kind: GitRepository
    name: okdp-sandbox
  path: ./clusters/sandbox/infra/cloudnative-pg
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: ConfigMap
        name: namespace-vars
