# Production cluster variables
# Same structure as sandbox, different values
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  # Override for production
  OKDP_INGRESS_SUFFIX: "okdp.production.example.com"
  OKDP_INGRESS_CLASS: "nginx"
  OKDP_CLUSTER_ISSUER: "letsencrypt-prod"
  OKDP_CA_COMMON_NAME: "OKDP Production CA"
  OKDP_CA_ORGANIZATION: "DGFiP"
  OKDP_CA_COUNTRY: "FR"
  OKDP_CA_VALIDITY: "8760h"
  OKDP_STORAGE_CLASS_DATA: "gp3"
  OKDP_STORAGE_CLASS_WORKSPACE: "gp3"
  OKDP_DB_HOST: "postgresql-instance-rw.cnpg-system.svc.cluster.local"
  OKDP_DB_PORT: "5432"
  OKDP_HTTP_PROXY: ""
  OKDP_HTTPS_PROXY: ""
  OKDP_NO_PROXY: ""
