# OKDP credential secrets
# WARNING: Sandbox credentials. Use Vault/External Secrets for production.
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-hms-db
type: Opaque
stringData:
  username: hms
  password: hms123
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-hms-s3
type: Opaque
stringData:
  accessKey: hms_access
  secretKey: hms_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-superset-db
type: Opaque
stringData:
  username: superset
  password: superset123
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-superset-secret-key
type: Opaque
stringData:
  superset_secret_key: "change-me-in-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-superset-examples-db
type: Opaque
stringData:
  username: examples
  password: examples123
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-redis
type: Opaque
stringData:
  username: ""
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-keycloak-db
  namespace: keycloak
type: Opaque
stringData:
  username: keycloak
  password: keycloak123
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-seaweedfs-db
type: Opaque
stringData:
  username: seaweedfs
  password: seaweedfs123
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-oidc
type: Opaque
stringData:
  client_id: confidential-oidc-client
  client_secret: secret1
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-airflow-db
type: Opaque
stringData:
  username: airflow
  password: airflow123
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-spark-history-s3
type: Opaque
stringData:
  accessKey: spark_access
  secretKey: spark_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-trino-s3
type: Opaque
stringData:
  S3_ACCESS_KEY: trino_access
  S3_SECRET_ACCESS: trino_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-jupyter-s3
type: Opaque
stringData:
  S3_ACCESS_KEY: jupyter_access
  S3_SECRET_KEY: jupyter_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-airflow-s3
type: Opaque
stringData:
  accessKey: airflow_access
  secretKey: airflow_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: creds-examples-s3
type: Opaque
stringData:
  S3_ACCESS_KEY: examples_access
  S3_SECRET_KEY: examples_secret
