# Role: Certificates
# Deploys cert-manager + ClusterIssuers
# Apps that need TLS dependsOn this role
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: role-certificates
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sources
  sourceRef:
    kind: GitRepository
    name: okdp-sandbox
  path: ./clusters/sandbox/infra/cert-manager
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
