# Overlay: with-proxy
# Adds proxy environment variables to spark-history-server and spark-web-proxy
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: spark-history-server
    patch: |
      - op: add
        path: /spec/values/extraEnvs/-
        value:
          name: HTTP_PROXY
          value: "${OKDP_HTTP_PROXY}"
      - op: add
        path: /spec/values/extraEnvs/-
        value:
          name: HTTPS_PROXY
          value: "${OKDP_HTTPS_PROXY}"
      - op: add
        path: /spec/values/extraEnvs/-
        value:
          name: NO_PROXY
          value: "${OKDP_NO_PROXY}"
